spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/novikova'
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true












